services:
  frontend:
    build: .
    container_name: dynecron_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - dynecron_network

networks:
  dynecron_network:
    external: true
    name: dynecron_network